### ISSUE TITLE
'pysam.libcsamfile.Samfile' object has no attribute 'next'

### ISSUE THREAD

**Issue by drpatelh** [pysam-developers/pysam#861]
Hi! Thank you for developing and maintaining this great tool. I have been using it for a number of years now and think its invaluable to anyone working with NGS data.

I have decided to take the plunge and update to using a Python 3 conda environment (Pysam v0.15.2; Python v3.7.3). However, when I do this a custom script I have written ([bampe_rm_orphan.py](https://github.com/drpatelh/nf-core-atacseq/blob/33c09f970ab78f37ac6f0f039432922a16923bd5/bin/bampe_rm_orphan.py)) fails with the following error:
```
  Traceback (most recent call last):
    File "nfcore/atacseq/bin/bampe_rm_orphan.py", line 149, in <module>
      bampe_rm_orphan(BAMIn=args.BAM_INPUT_FILE,BAMOut=args.BAM_OUTPUT_FILE,onlyFRPairs=args.ONLY_FR_PAIRS)
    File "nfcore/atacseq/bin/bampe_rm_orphan.py", line 66, in bampe_rm_orphan
      currRead = SAMFin.next()
  AttributeError: 'pysam.libcsamfile.Samfile' object has no attribute 'next'
```

I have tried to look around on google-groups, release notes, and here for some indication as to how to fix this but havent had much joy. I suspect the script is now outdated and I would be more than grateful I you can provide any comments/improvements. 

The input to the script is a paired-end BAM file sorted by name (no index file) and the idea is to remove any reads where the mate is not present in the BAM file. These would have been removed through prior filtering steps in the pipeline.

The same version of Pysam (v0.15.2) was working in a Python 2 environment (v2.7.15).

**Comment by drpatelh** [comment]
Ok. Ive found a fix by changing the syntax to `fetch` the regions in combination with using `iter.__next__()` instead. Updated [bampe_rm_orphan.py](https://github.com/drpatelh/nf-core-atacseq/blob/25b2fc408480ee8abd2c051c35438c36128dc267/bin/bampe_rm_orphan.py) script gives exactly the same result with both Python 2 and 3! 

Closing this issue but suggestions regarding the implementation more than welcome if time permits. Thank you!

**Comment by bioinformed** [comment]
better to use `next(foo)` vs. `foo.next()` or `foo.__next__()`.  The former
is the idiomatic way to do it in Python 3.

**Comment by drpatelh** [comment]
Thanks @bioinformed ! I'll give that a go.
