### ISSUE TITLE
Build error on linux machines [current version]

### ISSUE THREAD

**Issue by DSLituiev** [pysam-developers/pysam#139]
Hi, I am trying to build pysam on (1) my Ubuntu 14 machine, (2) Centos  (with cython 0.14) and (3) Mac Yosemite.  Mac works well. However,..

Under Ubuntu the compilation  failed before cython (latest 0.20.1post0) has been installed. Even after. I cannot build the current version, though v0.7.5 from google code does compile.

So what I get:
 
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    from libc.stdint cimport int8_t, int16_t, int32_t, int64_t
    from libc.stdint cimport uint8_t, uint16_t, uint32_t, uint64_t
    from libc.stdlib cimport malloc, calloc, realloc, free
    from libc.string cimport memcpy, memcmp, strncpy, strlen, strdup
    from libc.stdio cimport FILE, printf
    from posix.types cimport off_t
    ^
    ------------------------------------------------------------
    
    pysam/chtslib.pxd:6:0: 'posix.types.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    from libc.stdint cimport int8_t, int16_t, int32_t, int64_t
    from libc.stdint cimport uint8_t, uint16_t, uint32_t, uint64_t
    from libc.stdlib cimport malloc, calloc, realloc, free
    from libc.string cimport memcpy, memcmp, strncpy, strlen, strdup
    from libc.stdio cimport FILE, printf
    from posix.types cimport off_t
    ^
    ------------------------------------------------------------
    
    pysam/chtslib.pxd:6:0: 'off_t.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    from libc.stdint cimport int8_t, int16_t, int32_t, int64_t
    from libc.stdint cimport uint8_t, uint16_t, uint32_t, uint64_t
    from libc.stdlib cimport malloc, calloc, realloc, free
    from libc.string cimport memcpy, memcmp, strncpy, strlen, strdup
    from libc.stdio cimport FILE, printf
    from posix.types cimport off_t
                            ^
    ------------------------------------------------------------
    
    pysam/chtslib.pxd:6:25: Name 'off_t' not declared in module 'posix.types'
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        void hclearerr(hFILE *fp)
    
        # @abstract  Reposition the read/write stream offset
        # @return    The resulting offset within the stream (as per lseek(2)),
        #   or negative if an error occurred.
        off_t hseek(hFILE *fp, off_t offset, int whence)
       ^
    ------------------------------------------------------------
    
    pysam/chtslib.pxd:100:4: 'off_t' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        void hclearerr(hFILE *fp)
    
        # @abstract  Reposition the read/write stream offset
        # @return    The resulting offset within the stream (as per lseek(2)),
        #   or negative if an error occurred.
        off_t hseek(hFILE *fp, off_t offset, int whence)
                              ^
    ------------------------------------------------------------
    
    pysam/chtslib.pxd:100:27: 'off_t' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        #   or negative if an error occurred.
        off_t hseek(hFILE *fp, off_t offset, int whence)
    
        # @abstract  Report the current stream offset
        # @return    The offset within the stream, starting from zero.
        off_t htell(hFILE *fp)
       ^
    ------------------------------------------------------------
    
    pysam/chtslib.pxd:104:4: 'off_t' is not a type identifier
    building 'pysam.csamfile' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE= -Ipysam -Isamtools -Ihtslib -I/usr/include/python2.7 -c pysam/csamfile.c -o build/temp.linux-x86_64-2.7/pysam/csamfile.o -Wno-error=declaration-after-statement -DSAMTOOLS=1
    pysam/csamfile.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
     #error Do not use this file, it is the result of a failed Cython compilation.
      ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by AndreasHeger** [comment]
Thanks, which cython version are you using?
I think posix.types might be a new addition and possibly the requirements in setup.py are out-of-date.

Best wishes,
Andreas

**Comment by DSLituiev** [comment]
Ubuntu 14:
Cython version 0.20.1post0

CentOS release 6.6 (Final)  // not Red Hat indeed
Cython version 0.14.1

**Comment by landesfeind** [comment]
Hi, just ran into the same problem. I believe the Cython requirement should be updated to 0.21a1 or higher. The types.pxd has been added in cython/cython@4345655e401b491852967a9f4d5665acfa51e005

**Comment by hcraT** [comment]
Hi,
I run into the problem as well.
A quick and dirty fix that worked on ubuntu 14.04 was to change pysam/chtslib.pxd:6 from:
```cython
    from posix.types cimport off_t
```
to:
```cython
    from posix.unistd cimport off_t
```
I know that this is bad but it works if you just need to compile pysam.

**Comment by AndreasHeger** [comment]
Thanks all, cython requirement is >=0.22 in pysam 0.8.5 - closing for now.
