### ISSUE TITLE
Does not build with cython 0.23

### ISSUE THREAD

**Issue by outpaddling** [pysam-developers/pysam#164]
Same problem on CentOS 6.7 and FreeBSD 10.1 with pysam 0.8.3 and master.

Any suggestions?

Thanks,

    Jason

cc -DNDEBUG -O2 -pipe -fstack-protector -fno-strict-aliasing -fPIC -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE= -Ihtslib -Ihtslib -I/usr/local/include/python2.7 -c pysam/cbcf.c -o build/temp.freebsd-10.1-RELEASE-p16-amd64-2.7/pysam/cbcf.o -Wno-error=declaration-after-statement -DSAMTOOLS=1
pysam/cbcf.c:1984:67: error: must use 'enum' tag to refer to type
      'htsFormatCategory'
static CYTHON_INLINE PyObject* __Pyx_PyInt_From_htsFormatCategory(htsFormatCate...
                                                                  ^
                                                                  enum 
pysam/cbcf.c:1986:64: error: must use 'enum' tag to refer to type
      'htsExactFormat'
static CYTHON_INLINE PyObject* __Pyx_PyInt_From_htsExactFormat(htsExactF...
                                                               ^
                                                               enum 
pysam/cbcf.c:1990:64: error: must use 'enum' tag to refer to type
      'htsCompression'
static CYTHON_INLINE PyObject* __Pyx_PyInt_From_htsCompression(htsCompre...
                                                               ^
                                                               enum

**Comment by dannon** [comment]
@outpaddling Doesn't help you get it compiled with 0.23, but it may be useful to know that it still works fine with 0.22.1.  We're observing the same issue here, and downgraded Cython as a temporary workaround.

**Comment by outpaddling** [comment]
Thanks - I actually discovered the problem when I upgraded Cython from 0.22 to 0.23.  Running 0.22 for a while longer probably won't be a major inconvenience.  Both the package managers I use are on 0.23 now, but I haven't run into any dependency issues using 0.22 so far.

**Comment by AndreasHeger** [comment]
Thanks, I am looking at this. Might also explain why travis is failing.

**Comment by AndreasHeger** [comment]
Fixed, 6efb22b1a3ee4bc57a691f163b456b417da56db3
