### ISSUE TITLE
OSX with no lzma.h gives os/lzma_stub.h file not found on pip install only

### ISSUE THREAD

**Issue by mp15** [pysam-developers/pysam#645]
For some reason when I try and build from current pip pysam release on OS X without lzma.h specifically installed I get the following error, I think pysam might be forgetting to copy the lzma_stub into the wheel build dir?

```
  gcc -fPIC -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -O2 -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -I/private/var/folders/03/3h2pdngd2k3d9_h3cb_mv554000dhq/T/pip-build-VjPOxm/pysam/htslib -I/private/var/folders/03/3h2pdngd2k3d9_h3cb_mv554000dhq/T/pip-build-VjPOxm/pysam/samtools -I/private/var/folders/03/3h2pdngd2k3d9_h3cb_mv554000dhq/T/pip-build-VjPOxm/pysam/samtools/lz4 -I/private/var/folders/03/3h2pdngd2k3d9_h3cb_mv554000dhq/T/pip-build-VjPOxm/pysam/bcftools -I/private/var/folders/03/3h2pdngd2k3d9_h3cb_mv554000dhq/T/pip-build-VjPOxm/pysam/pysam -I/private/var/folders/03/3h2pdngd2k3d9_h3cb_mv554000dhq/T/pip-build-VjPOxm/pysam -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c htslib/cram/cram_io.c -o build/temp.macosx-10.5-intel-2.7/htslib/cram/cram_io.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
  htslib/cram/cram_io.c:63:10: fatal error: 'os/lzma_stub.h' file not found
  #include "os/lzma_stub.h"
           ^
  1 error generated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pysam
```
Curiously I don't get this error when I build using setup.py.

**Comment by jingwen** [comment]
I have the exact same error message when I install pysam 0.14, however pip installation works quite fine on pysam 0.13

**Comment by julalipa** [comment]
Hi, I can confirm that I am experiencing the same issue as above and that pip installation works fine with pysam 0.13.

**Comment by timothymillar** [comment]
I have the same issue with anaconda python (3.6.5) on OSX. pysam 0.13 works fine

**Comment by genomics-geek** [comment]
I also have the same issue.  I was trying to set up [pybamview](https://github.com/mgymrek/pybamview) and got this error when it tried to intstall pysam.

Python 3.5.2
OSX 10.11.6 El Capitan

**Comment by jkbonfield** [comment]
Is there a difference between pip and non-pip install as to whether they run ./configure before make?  Htslib ships with a Makefile that works even if configure hasn't been run, but that default Makefile declares HAVE_LZMA and so attempts to use the system lzma.h.  The configure script detects this and if not defined it'll use an internal stub file declaring the few symbols it needs.

Hence without the dev package installed, "make" will fail while "./configure;make" will not.

If non-pip isn't using configure then this is an error as the configure script also enables other important features, such as support for https (needed for remote CRAM references from EBI).

**Comment by XiaoMutt** [comment]
same issue with anaconda python 2.7

**Comment by reskejak** [comment]
FYI - also just experienced this with pysam 0.15 on MAC OS X Mojave 10.14.1 via `pip install pysam`. However, `pip install pysam==0.13` worked fine.

**Comment by p-lally** [comment]
I'm in the same boat as reskejak. OS X Mojave 10.14, Python 2.7.10.  Installing pysam 0.13 also worked for me.
