### ISSUE TITLE
Inconsistent htslib version dependencies in docs

### ISSUE THREAD

**Issue by winni2k** [pysam-developers/pysam#619]
There are a bunch of places in the pysam documentation where the htslib version that `pysam 0.13.0` depends on is specified. 

According to:

- the [release notes](https://pysam.readthedocs.io/en/latest/release.html?highlight=htslib) it's `htslib 1.6.0`
- the [main readthedocs page](https://pysam.readthedocs.io/en/latest/index.html) it's `htslib 1.3.0`
- the [pypi page](https://pypi.python.org/pypi/pysam/0.13) it's `htslib 1.4.1`

I can confirm that `pysam 0.13.0` fails to compile with `htslib 1.4.1` if I link it manually against a homebrew install version on my mac:
```fish
set -x HTSLIB_LIBRARY_DIR /usr/local/Cellar/htslib/1.4.1/lib 
set -x HTSLIB_INCLUDE_DIR /usr/local/Cellar/htslib/1.4.1/include
pip install pysam
```

, which fails with
```
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -Ipysam -I. -I/private/var/folders/py/9zg6845j2gb664dqkw24wn4w0000gn/T/pip-build-atzru6es/pysam/samtools -I/usr/local/Cellar/htslib/1.4.1/include -I/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c samtools/bam_sort.c.pysam.c -o build/temp.macosx-10.13-x86_64-3.6/samtools/bam_sort.c.pysam.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
    samtools/bam_sort.c.pysam.c:45:10: fatal error: 'htslib/hts_os.h' file not found
    #include "htslib/hts_os.h"
             ^~~~~~~~~~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1
    
```

As far as I can tell, `htslib/hts_os.h` is not part of `htslib 1.4.1`

**Comment by AndreasHeger** [comment]
Thanks, good point, will update the docs.

**Comment by AndreasHeger** [comment]
Unfortunately, pysam is quite tightly coupled to htslib versions. The release notes have the best matches.

**Comment by winni2k** [comment]
Cheers.
