### ISSUE TITLE
Fails to build with Python3.12

### ISSUE THREAD

**Issue by tillea** [pysam-developers/pysam#1253]
Hi,
the Debian packaged pysam received a [bug report](bugs.debian.org/1057809) about build failures with Python3.12.  You can find a [full build log](https://salsa.debian.org/med-team/python-pysam/-/jobs/5017928#L448) in our CI.  It starts with

    x86_64-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -g -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -g -fwrapv -O2 -g -O2 -ffile-prefix-  map=/builds/med-team/python-pysam/debian/output/source_dir=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/builds/med-team/      python-pysam/debian/output/source_dir/pysam -I/usr/include -I/builds/med-team/python-pysam/debian/output/source_dir/samtools -I/builds/med-team/python-pysam/debian/output/source_dir/samtools/lz4 -I/builds/med-team/python-  pysam/debian/output/source_dir/bcftools -I/builds/med-team/python-pysam/debian/output/source_dir -I/usr/include/python3.12 -c pysam/libchtslib.c -o build/temp.linux-x86_64-cpython-312/pysam/libchtslib.o -Wno-unused -Wno-   strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
    pysam/libchtslib.c: In function ‘__pyx_f_5pysam_10libchtslib_set_verbosity’:
    pysam/libchtslib.c:1387:32: error: ‘_PyCFrame’ has no member named ‘use_tracing’
     1387 |      (unlikely((tstate)->cframe->use_tracing) &&\
          |                                ^~
    pysam/libchtslib.c:958:43: note: in definition of macro ‘unlikely’
      958 |   #define unlikely(x) __builtin_expect(!!(x), 0)
          |                                           ^
    pysam/libchtslib.c:1426:15: note: in expansion of macro ‘__Pyx_IsTracing’
     1426 |           if (__Pyx_IsTracing(tstate, 1, 1)) {\
          |               ^~~~~~~~~~~~~~~

It would be great if you could adapt pysam to Python3.12.
Kind regards, Andreas.

**Comment by tillea** [comment]
I've received a hint that when building with cython 3.0.6 the failure above is vanishing.  Thus I'm closing this issue.

**Comment by jmarshall** [comment]
Duplicate of Debian’s previous report, #1242.
