### ISSUE TITLE
Error when installing related to missing samtools/config.h file

### ISSUE THREAD

**Issue by mfoll** [pysam-developers/pysam#257]
Hi, 

I have the following error when trying to install pysam. I am using Centos 6.6 and linking to an external htslib because of this issue recently resolved in htslib: https://github.com/samtools/htslib/commit/2805ae8041f2d49b889d0b4f54c53070e4791dbb.

```bash
export HTSLIB_LIBRARY_DIR=/usr/local/lib
export HTSLIB_INCLUDE_DIR=/usr/local/include
pip install pysam

...

gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isamtools -Ibcftools -Ipysam -I. -I/usr/local/include -I/opt/rh/python27/root/usr/include/python2.7 -c samtools/bam_tview_curses.c.pysam.c -o build/temp.linux-x86_64-2.7/samtools/bam_tview_curses.c.pysam.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
    samtools/bam_tview_curses.c.pysam.c:28:20: fatal error: config.h: No such file or directory
     #include <config.h>
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```

It seems related to commit 567069618d6f96385328db06affbe2363bb1c0bb where the `config.h` has been deleted.

Thanks for your help!

**Comment by mfoll** [comment]
Note that it works fine with pysam v0.8.4

**Comment by AndreasHeger** [comment]
Thanks, interesting. I have no config.h in the samtools directory and it builds fine. Indeed, I get the following warning:

```
samtools/bam_tview_curses.c.pysam.c:343:2: warning: #warning "No curses library is available; tview with curses is disabled." [-Wcpp]
 #warning "No curses library is available; tview with curses is disabled."
  ^
```

The difference is that my compile command contains ```-Ihtslib```, which yours does not.

I think a quick fix in your case would be to do: 
```
touch samtools/config.h
```
and then do 

```
python setup.py install.
```

I will make sure an empty config.h is created when htslib is external.

**Comment by AndreasHeger** [comment]
Closed, see  55f5d8c
