### ISSUE TITLE
pysam-0.12.0.1: pysam/libcalignedsegment.c:12199:20: error: 'bam1_core_t' has no member named 'l_extranul'

### ISSUE THREAD

**Issue by mmokrejs** [pysam-developers/pysam#545]
Hi,
  I cannot compile on Gentoo Linux this version from sources with gcc-4.9.4. The only difference to vanilla 0.12.0.1 is pysam-0.12-fix-buildsystem.patch . See https://archives.gentoo.org/gentoo-commits/message/9f7aec7e1b34fa685ebd77eb8a6c8728 if it is related at all. Eventually contact @SoapGentoo for more details.

x86_64-pc-linux-gnu-gcc -O2 -pipe -O2 -pipe -march=native -ftree-vectorize -fPIC -Ipysam -I. -I/apps/gentoo/var/tmp/portage/sci-biology/pysam-0.12.0.1/work/pysam-0.12.0.1/samtools -I/apps/gentoo/usr/include -I/apps/gentoo/usr/include/python2.7 -c pysam/libcalignedsegment.c -o /apps/gentoo/var/tmp/portage/sci-biology/pysam-0.12.0.1/work/pysam-0.12.0.1-python2_7/temp.linux-x86_64-2.7/pysam/libcalignedsegment.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
pysam/libcalignedsegment.c: In function ‘__pyx_pf_5pysam_18libcalignedsegment_14AlignedSegment_10query_name_2__set__’:
pysam/libcalignedsegment.c:12199:20: error: ‘bam1_core_t’ has no member named ‘l_extranul’
   __pyx_v_src->core.l_extranul = __pyx_v_l_extranul;
                    ^
error: command 'x86_64-pc-linux-gnu-gcc' failed with exit status 1
 * ERROR: sci-biology/pysam-0.12.0.1::gentoo failed (install phase):

**Comment by AndreasHeger** [comment]
Thanks, is this building with the included htslib or an external htslib version?

**Comment by SoapGentoo** [comment]
We always use external htslib in Gentoo.

**Comment by AndreasHeger** [comment]
Thanks. Which version is it? l_extranul  seems to be defined:
https://github.com/samtools/htslib/search?utf8=%E2%9C%93&q=extranul&type=

**Comment by mmokrejs** [comment]
In which htslib version was that added? Does pysam properly check for the version? Just a guess.

The machine I faced this problem is currently in maintenance so I cannot check the logs now.

On a *different* host I can compile now pysam-0.12.0.1 against htslib-1.5. I was at pysam-0.9.0 and htslib-1.3.1:

[ebuild     U  ] sci-libs/htslib-1.5:0/2::gentoo [1.3.1:0/0::gentoo] USE="bzip2%* lzma%* -curl% -static-libs" 1027 KiB
[ebuild     U  ] sci-biology/pysam-0.12.0.1::gentoo [0.9.0::gentoo] PYTHON_TARGETS="python2_7 python3_4 -python3_5 -python3_6%" 2610 KiB

Does pysam-0.12.0.1 require htslib-1.5 and is known not to work with say htslib-1.3.1?

**Comment by kyleabeauchamp** [comment]
AFAIK, each pysam version should be pinned to a specific HTSLib version.  It is not permitted to mix and match.

**Comment by mmokrejs** [comment]
You should at least start maintaining a ./pysam/NEWS file and recording in it current requirements. htslib-1.2 up to 1.6 should be mutually interchangeable as they provide same library version. It would be an interesting read to see what pysam needs from whichever htslib version and what is not present in a *previous* version of htslib.

**Comment by mmokrejs** [comment]
Uh, there is  ./pysam/requirements.txt , quite outdated and the INSTALL file as well.

**Comment by AndreasHeger** [comment]
Hi, @mmokrejs , apologies. pysam is generally updated following a htslib version change, though occasionally there are between-version releases. The record for this is in doc/release.txt so that the release notes are published at http://pysam.readthedocs.io/en/latest/release.html.

Specificially, the dependencies are:

pysam-0.12.0 -> htslib 1.5
pysam-0.11.0 -> htslib 1.4
pysam-0.9.0 -> htslib 1.3

Good point about the NEWS file, will add comments in there and also update the INSTALL. The requirements.txt file is up-to-date, but of course only covers pip dependencies.

**Comment by kyleabeauchamp** [comment]
If possible, I vote that we try to consolidate / remove some docs files that seem out of date or redundant.

**Comment by AndreasHeger** [comment]
Thansk, @kyleabeauchamp will update the INSTALL file and refer to release.rst in a NEWS file to avoid duplication.

**Comment by mmokrejs** [comment]
@AndreasHeger Wow! Exactly what I/we were looking for when trying to remove bundled "anonymous" `htslib` code from `pysam` source tarball. Either `INSTALL` would be enough to list requirements and `./pysam/requirements.txt `could be dropped. I would still prefer `NEWS` or `Changelog` to exist to keep track of the requirements and development altogether. Gentoo Linux is not the only distro trying to keep package requirement listings sane.

**Comment by AndreasHeger** [comment]
A version check of an external htslib might also be useful to flag mismatches up early. Not sure how to get the version within a setup.py context.

@mmokrejs, thanks, will aim to make the package more packageable.

**Comment by mmokrejs** [comment]
> A version check of an external htslib might also be useful to flag mismatches up early. Not sure how to
> get the version within a setup.py context.

@SoapGentoo is more advanced developer and I bet he will know How to do that. ;)

**Comment by mmokrejs** [comment]
> Specificially, the dependencies are:
>
> pysam-0.12.0 -> htslib 1.5
> pysam-0.11.0 -> htslib 1.4
> pysam-0.9.0 -> htslib 1.3

Provided I had `pysam-0.9.0` and `htslib-1.3.1` ... did you @AndreasHeger eventually want to say the following?

```
Specificially, the dependencies are:

pysam-0.12.0 >= htslib 1.5
pysam-0.11.0 >= htslib 1.4
pysam-0.9.0 >= htslib 1.3
```
